name: Build and Package macOS App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install -g yarn
          yarn install

      - name: Build and Package for macOS
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run package-mac

      - name: Create Git Tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag v1.0.${{ github.run_number }}
          git push origin v1.0.${{ github.run_number }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload .dmg and .zip files to Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}
          files: release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
